data:
  data_root: "C:\\Users\\sokol\\OneDrive\\Pulpit\\SEM_8\\magisterka\\new_data_1\\data"
  annotation_root: "C:\\Users\\sokol\\OneDrive\\Pulpit\\SEM_8\\magisterka\\new_data_1\\data\\annotations"
  slice_length: 0.1 # seconds
  sample_rate: 48000
  test_split: 0.2
  val_split: 0.2
  random_seed: 42
  num_workers: 0

model:
  num_classes: 6 # Q: Maybe can be read from classes?
  classes: [25, 30, 35, 40, 45, 50]
  pretrained: true

training:
  batch_size: 16
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler_step_size: 15
  scheduler_gamma: 0.1
  model_save_path: "models/audio_temperature_classifier.pth"

augmentation:
  enabled: true
  gain_range: [-5, 5]  # dB
  pitch_shift_range: [-3, 3]  # semitones
  time_stretch_factors: [0.8, 0.9, 1.0, 1.1, 1.2]