data:
  data_root: "C:\\path_to_data_root"
  annotation_root: "C:\\path_to_annotation_root"
  slice_length: 0.1 # seconds
  overlap: 0.5 # 0.5 for 50% overlap
  sample_rate: 48000
  test_split: 0.2
  val_split: 0.2
  random_seed: 42
  equalize_num_samples: false
  num_workers: 0
  should_interpolate: true # for regression only

model:
  pretrained: true
  type: "regression"  # supports classification and regression
  # for classification
  num_classes: 6
  classes: [25, 30, 35, 40, 45, 50]

training:
  batch_size: 16
  num_epochs: 50
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler_step_size: 15
  scheduler_gamma: 0.1
  model_save_path: "models/model_save_name.pth"

augmentation:
  enabled: true
  gain_range: [-5, 5]  # dB
  pitch_shift_range: [-3, 3]  # semitones
  time_stretch_factors: [0.8, 0.9, 1.0, 1.1, 1.2]

preprocessing:
  normalize: "peak"
  filters:
    - type: "bandpass"
      kwargs:
        lowcut: 50
        highcut: 8000
        order: 5

  denoising:
    - method: "wavelet"
      kwargs:
        wavelet: "db4"
        level: 3
        threshold_factor: 0.05
